server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nexabank_accounts}
    username: ${SPRING_DATASOURCE_USERNAME:nexabank}
    password: ${SPRING_DATASOURCE_PASSWORD:nexabank123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  producer:
    topics:
      account-created: nexabank.account.created

jwt:
  secret: ${JWT_SECRET:nexabank-dev-secret-at-least-256-bits-long!}
  expiration-ms: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
