server:
  port: 8082

spring:
  application:
    name: transaction-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nexabank_transactions}
    username: ${SPRING_DATASOURCE_USERNAME:nexabank}
    password: ${SPRING_DATASOURCE_PASSWORD:nexabank123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: nexabank
    password: nexabank123
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  producer:
    topics:
      transaction-completed: nexabank.transaction.completed

activemq:
  queue:
    transaction-events: nexabank.transaction.events

ndm:
  outbound-directory: ./target/ndm-outbound
  inbound-directory: ./target/ndm-inbound
  batch-cron: "0 0 1 * * ?"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
