-- =============================================================================
-- NexaBank Transaction Service — Flyway Migration V1
-- Oracle-compatible DDL
-- =============================================================================

CREATE SEQUENCE IF NOT EXISTS SEQ_TRANSACTION_ID
    START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS SEQ_LEDGER_ID
    START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID                  BIGINT          DEFAULT NEXTVAL('SEQ_TRANSACTION_ID') PRIMARY KEY,
    REFERENCE_NUMBER    VARCHAR(36)     NOT NULL,
    SOURCE_ACCOUNT_ID   BIGINT          NOT NULL,
    DEST_ACCOUNT_ID     BIGINT,
    TRANSACTION_TYPE    VARCHAR(20)     NOT NULL,
    AMOUNT              NUMERIC(19, 4)  NOT NULL,
    CURRENCY            CHAR(3)         NOT NULL DEFAULT 'USD',
    STATUS              VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    DESCRIPTION         VARCHAR(500),
    CREATED_AT          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT        TIMESTAMP,
    CREATED_BY          VARCHAR(255)    NOT NULL,

    CONSTRAINT UQ_TXN_REFERENCE   UNIQUE (REFERENCE_NUMBER),
    CONSTRAINT CK_TXN_TYPE        CHECK (TRANSACTION_TYPE IN ('DEPOSIT','WITHDRAWAL','TRANSFER')),
    CONSTRAINT CK_TXN_STATUS      CHECK (STATUS IN ('PENDING','COMPLETED','FAILED','REVERSED')),
    CONSTRAINT CK_TXN_AMOUNT      CHECK (AMOUNT > 0)
);

CREATE TABLE IF NOT EXISTS LEDGER_ENTRIES (
    ID              BIGINT          DEFAULT NEXTVAL('SEQ_LEDGER_ID') PRIMARY KEY,
    TRANSACTION_ID  BIGINT          NOT NULL,
    ACCOUNT_ID      BIGINT          NOT NULL,
    ENTRY_TYPE      VARCHAR(6)      NOT NULL,
    AMOUNT          NUMERIC(19, 4)  NOT NULL,
    BALANCE_AFTER   NUMERIC(19, 4)  NOT NULL,
    POSTED_AT       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_LEDGER_TRANSACTION FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS(ID),
    CONSTRAINT CK_LEDGER_ENTRY_TYPE  CHECK (ENTRY_TYPE IN ('DEBIT', 'CREDIT'))
);

CREATE INDEX IF NOT EXISTS IDX_TXN_SOURCE_ACCOUNT   ON TRANSACTIONS(SOURCE_ACCOUNT_ID);
CREATE INDEX IF NOT EXISTS IDX_TXN_CREATED_AT       ON TRANSACTIONS(CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_LEDGER_ACCOUNT        ON LEDGER_ENTRIES(ACCOUNT_ID);
CREATE INDEX IF NOT EXISTS IDX_LEDGER_TRANSACTION    ON LEDGER_ENTRIES(TRANSACTION_ID);
