-- =============================================================================
-- NexaBank Notification Service — Flyway Migration V1
-- =============================================================================

CREATE SEQUENCE IF NOT EXISTS SEQ_NOTIFICATION_ID
    START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;

CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID              BIGINT          DEFAULT NEXTVAL('SEQ_NOTIFICATION_ID') PRIMARY KEY,
    CUSTOMER_ID     BIGINT          NOT NULL,
    CHANNEL         VARCHAR(20)     NOT NULL DEFAULT 'EMAIL',
    TYPE            VARCHAR(50)     NOT NULL,
    SUBJECT         VARCHAR(255)    NOT NULL,
    BODY            TEXT            NOT NULL,
    IS_READ         BOOLEAN         NOT NULL DEFAULT FALSE,
    SENT_AT         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    READ_AT         TIMESTAMP,
    SOURCE_TOPIC    VARCHAR(100),
    CORRELATION_ID  VARCHAR(36),

    CONSTRAINT CK_NOTIF_CHANNEL CHECK (CHANNEL IN ('EMAIL', 'SMS', 'IN_APP'))
);

CREATE INDEX IF NOT EXISTS IDX_NOTIF_CUSTOMER ON NOTIFICATIONS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_NOTIF_SENT_AT  ON NOTIFICATIONS(SENT_AT);
CREATE INDEX IF NOT EXISTS IDX_NOTIF_IS_READ  ON NOTIFICATIONS(IS_READ);
