-- =============================================================================
-- NexaBank Loan Service — Flyway Migration V1
-- =============================================================================

CREATE SEQUENCE IF NOT EXISTS SEQ_LOAN_ID
    START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;

CREATE TABLE IF NOT EXISTS LOAN_APPLICATIONS (
    ID                  BIGINT          DEFAULT NEXTVAL('SEQ_LOAN_ID') PRIMARY KEY,
    CUSTOMER_ID         BIGINT          NOT NULL,
    ACCOUNT_ID          BIGINT          NOT NULL,
    LOAN_TYPE           VARCHAR(30)     NOT NULL,
    REQUESTED_AMOUNT    NUMERIC(19, 4)  NOT NULL,
    TERM_MONTHS         INTEGER         NOT NULL,
    ANNUAL_INCOME       NUMERIC(19, 4)  NOT NULL,
    CREDIT_SCORE        INTEGER,
    STATUS              VARCHAR(20)     NOT NULL DEFAULT 'SUBMITTED',
    AI_DECISION         VARCHAR(20),
    AI_REASON           TEXT,
    REVIEWED_BY         VARCHAR(255),
    APPLIED_AT          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DECIDED_AT          TIMESTAMP,

    CONSTRAINT CK_LOAN_TYPE   CHECK (LOAN_TYPE IN ('PERSONAL','AUTO','MORTGAGE')),
    CONSTRAINT CK_LOAN_STATUS CHECK (STATUS IN ('SUBMITTED','AI_REVIEW','APPROVED','REJECTED','CANCELLED')),
    CONSTRAINT CK_LOAN_AMOUNT CHECK (REQUESTED_AMOUNT > 0)
);

CREATE INDEX IF NOT EXISTS IDX_LOAN_CUSTOMER ON LOAN_APPLICATIONS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_LOAN_STATUS   ON LOAN_APPLICATIONS(STATUS);
