-- =============================================================================
-- NexaBank Account Service — Flyway Migration V1
-- Oracle-compatible DDL (PostgreSQL-executable)
--
-- Oracle conventions used:
--   - UPPERCASE table/column names
--   - SEQUENCE objects for primary keys (not SERIAL/IDENTITY)
--   - NUMERIC(19,4) for monetary values (never FLOAT/DOUBLE)
--   - Named indexes with IDX_ prefix
-- =============================================================================

-- Sequences (Oracle-compatible — PostgreSQL supports SEQUENCE natively)
CREATE SEQUENCE IF NOT EXISTS SEQ_CUSTOMER_ID
    START WITH 1
    INCREMENT BY 1
    CACHE 1
    NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS SEQ_ACCOUNT_ID
    START WITH 1000
    INCREMENT BY 1
    CACHE 1
    NO CYCLE;

-- CUSTOMERS table
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID              BIGINT          DEFAULT NEXTVAL('SEQ_CUSTOMER_ID') PRIMARY KEY,
    EMAIL           VARCHAR(255)    NOT NULL,
    PASSWORD_HASH   VARCHAR(500)    NOT NULL,
    FIRST_NAME      VARCHAR(100)    NOT NULL,
    LAST_NAME       VARCHAR(100)    NOT NULL,
    PHONE           VARCHAR(20),
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP,

    CONSTRAINT UQ_CUSTOMERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_CUSTOMERS_STATUS CHECK (STATUS IN ('ACTIVE', 'SUSPENDED'))
);

-- ACCOUNTS table
CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ID              BIGINT          DEFAULT NEXTVAL('SEQ_ACCOUNT_ID') PRIMARY KEY,
    ACCOUNT_NUMBER  VARCHAR(20)     NOT NULL,
    ACCOUNT_TYPE    VARCHAR(20)     NOT NULL,
    BALANCE         NUMERIC(19, 4)  NOT NULL DEFAULT 0,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    INTEREST_RATE   NUMERIC(5, 4),
    OPENED_AT       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CLOSED_AT       TIMESTAMP,
    CUSTOMER_ID     BIGINT          NOT NULL,

    CONSTRAINT UQ_ACCOUNTS_NUMBER  UNIQUE (ACCOUNT_NUMBER),
    CONSTRAINT FK_ACCOUNTS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT CK_ACCOUNTS_TYPE    CHECK (ACCOUNT_TYPE IN ('CHECKING', 'SAVINGS')),
    CONSTRAINT CK_ACCOUNTS_STATUS  CHECK (STATUS IN ('ACTIVE', 'FROZEN', 'CLOSED')),
    CONSTRAINT CK_ACCOUNTS_BALANCE CHECK (BALANCE >= 0)
);

-- Indexes (named per Oracle convention)
CREATE INDEX IF NOT EXISTS IDX_ACCOUNTS_CUSTOMER ON ACCOUNTS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_EMAIL   ON CUSTOMERS(EMAIL);
